### ISSUE TITLE
Consider moving this to rpm-software-management organization?

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/distribution-gpg-keys#14]
As this is needed by mock for stuff, would you consider moving this repository to the rpm-software-management organization to make it easier to discover this and contribute to it?

**Comment by xsuchy** [comment]
I personally do not care. I talked to Dan Mach and he was not too keen to get it there. So I guess that I will keep it here. But if more people find it helpful to move the project I will be happy to try to persuade Dan once again.

**Comment by DaanDeMeyer** [comment]
@Conan-Kudo @xsuchy Can we reopen this? It would lend more credibility to the project if it was located under rpm-software-management.

**Comment by xsuchy** [comment]
Moved.
